#!/usr/bin/env bash
#This script is going to output best school 10 times and and hi after the 9th line.
i=1
while [ $i -le 10 ]; do
echo "Best School"
if [ $i -eq 9 ]; then
echo "Hi"
fi

((i++))
done
