#!/usr/bin/env bash
#This script is going to display best school on other line except on 8th and 4th iterations
i=1
while [ $i -le 10 ]; do
if [ $i -eq 4 ]; then
echo "bad luck" 
elif [ $i -eq 8 ]; then
echo "good luck" 
else
echo "Best School"
fi
((i++))

done
