#!/usr/bin/env bash
#This script will demonstrate use of while loop and case statememts to print output.
i=1
while [ $i -le 20 ]; do
echo $i

case $i in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;

esac
((i++))

done


